apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sb7k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sb7k
    app.kubernetes.io/part-of: tkrw-pr714-0075-0028-app
  name: devfile-sample-sb7k
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sb7k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sb7k
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0028-tenant/tkrw-pr714-0075-0028-app/devfile-sample-sb7k@sha256:e5aa4271b59bf2e56324211529b78379cc156bac5dcd5e3c27bd72cffd9abb56
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
